# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seti1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import signal
import threading
import time
from multiprocessing import process
import networkx as nx

import matplotlib
from PyQt5.QtWidgets import QApplication, QMainWindow

#matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_mainWindow(object):

    def __init__(self):
        self.graf = None
        self.ping_thread = None
        self.ping_process = None
        self.stop_threads = False


    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1029, 848)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 31, 21))
        self.label.setObjectName("label")
        self.ping_t = QtWidgets.QCheckBox(self.centralwidget)
        self.ping_t.setGeometry(QtCore.QRect(50, 40, 31, 21))
        self.ping_t.setObjectName("ping_t")
        self.ping_a = QtWidgets.QCheckBox(self.centralwidget)
        self.ping_a.setGeometry(QtCore.QRect(90, 40, 39, 20))
        self.ping_a.setObjectName("ping_a")
        self.ping_n = QtWidgets.QSpinBox(self.centralwidget)
        self.ping_n.setGeometry(QtCore.QRect(140, 40, 42, 22))
        self.ping_n.setMinimum(0)
        self.ping_n.setMaximum(1000)
        self.ping_n.setProperty("value", 0)
        self.ping_n.setObjectName("ping_n")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.label_2.setObjectName("label_2")
        self.ping_l = QtWidgets.QSpinBox(self.centralwidget)
        self.ping_l.setGeometry(QtCore.QRect(220, 40, 42, 22))
        self.ping_l.setMaximum(1024)
        self.ping_l.setObjectName("ping_l")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 40, 21, 21))
        self.label_3.setObjectName("label_3")
        self.ping_f = QtWidgets.QCheckBox(self.centralwidget)
        self.ping_f.setGeometry(QtCore.QRect(290, 40, 39, 20))
        self.ping_f.setObjectName("ping_f")
        self.ping_i = QtWidgets.QSpinBox(self.centralwidget)
        self.ping_i.setGeometry(QtCore.QRect(340, 40, 42, 22))
        self.ping_i.setMinimum(0)
        self.ping_i.setMaximum(1000)
        self.ping_i.setProperty("value", 0)
        self.ping_i.setObjectName("ping_i")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 40, 21, 21))
        self.label_4.setObjectName("label_4")
        self.ping_r = QtWidgets.QSpinBox(self.centralwidget)
        self.ping_r.setGeometry(QtCore.QRect(410, 40, 42, 22))
        self.ping_r.setMinimum(0)
        self.ping_r.setMaximum(9)
        self.ping_r.setProperty("value", 0)
        self.ping_r.setObjectName("ping_r")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 40, 21, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 40, 21, 21))
        self.label_6.setObjectName("label_6")
        self.ping_w = QtWidgets.QSpinBox(self.centralwidget)
        self.ping_w.setGeometry(QtCore.QRect(480, 40, 42, 22))
        self.ping_w.setMinimum(0)
        self.ping_w.setMaximum(999999)
        self.ping_w.setProperty("value", 0)
        self.ping_w.setObjectName("ping_w")
        self.ip = QtWidgets.QTextEdit(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(560, 30, 101, 41))
        self.ip.setObjectName("ip")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(670, 20, 61, 51))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_ping = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ping.setGeometry(QtCore.QRect(750, 40, 93, 28))
        self.pushButton_ping.setObjectName("pushButton_ping")

        self.pushButton_ping.clicked.connect(self.start_ping_thread)

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 55, 16))
        self.label_8.setObjectName("label_8")
        self.ipconfig_q = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_q.setGeometry(QtCore.QRect(70, 110, 41, 20))
        self.ipconfig_q.setObjectName("ipconfig_q")
        self.ipconfig_all = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_all.setGeometry(QtCore.QRect(110, 110, 41, 20))
        self.ipconfig_all.setObjectName("ipconfig_all")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 90, 61, 51))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.ipconfig_release_adapter = QtWidgets.QTextEdit(self.centralwidget)
        self.ipconfig_release_adapter.setGeometry(QtCore.QRect(160, 100, 91, 31))
        self.ipconfig_release_adapter.setObjectName("ipconfig_release_adapter")
        self.ipconfig_release_all = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_release_all.setGeometry(QtCore.QRect(330, 110, 171, 20))
        self.ipconfig_release_all.setObjectName("ipconfig_release_all")
        self.ipconfig_renew_adapter = QtWidgets.QTextEdit(self.centralwidget)
        self.ipconfig_renew_adapter.setGeometry(QtCore.QRect(510, 100, 91, 31))
        self.ipconfig_renew_adapter.setObjectName("ipconfig_renew_adapter")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(610, 90, 61, 51))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.ipconfig_renew_all = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_renew_all.setGeometry(QtCore.QRect(680, 110, 171, 20))
        self.ipconfig_renew_all.setObjectName("ipconfig_renew_all")
        self.ipconfig_flushdns = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_flushdns.setGeometry(QtCore.QRect(10, 150, 81, 20))
        self.ipconfig_flushdns.setObjectName("ipconfig_flushdns")
        self.ipconfig_displaydns = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_displaydns.setGeometry(QtCore.QRect(100, 150, 91, 20))
        self.ipconfig_displaydns.setObjectName("ipconfig_displaydns")
        self.ipconfig_registerdns = QtWidgets.QCheckBox(self.centralwidget)
        self.ipconfig_registerdns.setGeometry(QtCore.QRect(200, 150, 101, 20))
        self.ipconfig_registerdns.setObjectName("ipconfig_registerdns")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 140, 81, 51))
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.ipconfig_showclassid = QtWidgets.QTextEdit(self.centralwidget)
        self.ipconfig_showclassid.setGeometry(QtCore.QRect(310, 150, 91, 31))
        self.ipconfig_showclassid.setObjectName("ipconfig_showclassid")
        self.ipconfig_setclassid = QtWidgets.QTextEdit(self.centralwidget)
        self.ipconfig_setclassid.setGeometry(QtCore.QRect(500, 150, 91, 31))
        self.ipconfig_setclassid.setObjectName("ipconfig_setclassid")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(600, 140, 81, 51))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.ipconfig_setclassid_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.ipconfig_setclassid_2.setGeometry(QtCore.QRect(690, 150, 91, 31))
        self.ipconfig_setclassid_2.setObjectName("ipconfig_setclassid_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(790, 130, 101, 61))
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_ipconfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ipconfig.setGeometry(QtCore.QRect(910, 107, 93, 71))
        self.pushButton_ipconfig.setObjectName("pushButton_ipconfig")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 210, 55, 16))
        self.label_14.setObjectName("label_14")
        self.tracert_d = QtWidgets.QCheckBox(self.centralwidget)
        self.tracert_d.setGeometry(QtCore.QRect(70, 210, 41, 20))
        self.tracert_d.setObjectName("tracert_d")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(170, 210, 21, 21))
        self.label_15.setObjectName("label_15")
        self.tracert_h = QtWidgets.QSpinBox(self.centralwidget)
        self.tracert_h.setGeometry(QtCore.QRect(120, 210, 42, 22))
        self.tracert_h.setMinimum(0)
        self.tracert_h.setMaximum(999999)
        self.tracert_h.setProperty("value", 0)
        self.tracert_h.setObjectName("tracert_h")
        #self.label_16 = QtWidgets.QLabel(self.centralwidget)
        #self.label_16.setGeometry(QtCore.QRect(250, 210, 21, 21))
        #self.label_16.setObjectName("label_16")
        #self.tracert_j = QtWidgets.QSpinBox(self.centralwidget)
        #self.tracert_j.setGeometry(QtCore.QRect(200, 210, 42, 22))
        #self.tracert_j.setMinimum(0)
        #self.tracert_j.setMaximum(999999)
        #self.tracert_j.setProperty("value", 0)
        #self.tracert_j.setObjectName("tracert_j")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(330, 210, 21, 21))
        self.label_17.setObjectName("label_17")
        self.tracert_w = QtWidgets.QSpinBox(self.centralwidget)
        self.tracert_w.setGeometry(QtCore.QRect(280, 210, 42, 22))
        self.tracert_w.setMinimum(0)
        self.tracert_w.setMaximum(999999)
        self.tracert_w.setProperty("value", 0)
        self.tracert_w.setObjectName("tracert_w")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(470, 200, 61, 51))
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.tracert_ip = QtWidgets.QTextEdit(self.centralwidget)
        self.tracert_ip.setGeometry(QtCore.QRect(360, 210, 101, 41))
        self.tracert_ip.setObjectName("tracert_ip")
        self.pushButton_tracert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tracert.setGeometry(QtCore.QRect(540, 210, 93, 28))
        self.pushButton_tracert.setObjectName("pushButton_tracert")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 280, 31, 16))
        self.label_19.setObjectName("label_19")
        self.arp_s = QtWidgets.QCheckBox(self.centralwidget)
        self.arp_s.setGeometry(QtCore.QRect(50, 280, 41, 20))
        self.arp_s.setObjectName("arp_s")
        self.arp_d = QtWidgets.QCheckBox(self.centralwidget)
        self.arp_d.setGeometry(QtCore.QRect(100, 280, 41, 20))
        self.arp_d.setObjectName("arp_d")
        self.arp_a = QtWidgets.QCheckBox(self.centralwidget)
        self.arp_a.setGeometry(QtCore.QRect(150, 280, 41, 20))
        self.arp_a.setObjectName("arp_a")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(310, 270, 61, 51))
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.arp_inet_addr = QtWidgets.QTextEdit(self.centralwidget)
        self.arp_inet_addr.setGeometry(QtCore.QRect(200, 280, 101, 41))
        self.arp_inet_addr.setObjectName("arp_inet_addr")
        self.arp_eth_addr = QtWidgets.QTextEdit(self.centralwidget)
        self.arp_eth_addr.setGeometry(QtCore.QRect(380, 280, 101, 41))
        self.arp_eth_addr.setObjectName("arp_eth_addr")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(490, 270, 61, 51))
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.arp_if_addr = QtWidgets.QTextEdit(self.centralwidget)
        self.arp_if_addr.setGeometry(QtCore.QRect(560, 280, 101, 41))
        self.arp_if_addr.setObjectName("arp_if_addr")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(670, 270, 61, 51))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(850, 270, 61, 51))
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.arp__n_if_addr = QtWidgets.QTextEdit(self.centralwidget)
        self.arp__n_if_addr.setGeometry(QtCore.QRect(740, 280, 101, 41))
        self.arp__n_if_addr.setObjectName("arp__n_if_addr")
        self.pushButton_arp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arp.setGeometry(QtCore.QRect(920, 270, 93, 51))
        self.pushButton_arp.setObjectName("pushButton_arp")
        self.output = QtWidgets.QTextBrowser(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 350, 1011, 471))
        self.output.setObjectName("output")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.pushButton_ipconfig.clicked.connect(self.start_ipconfig_thread)
        self.pushButton_tracert.clicked.connect(self.start_tracert_thread)
        self.pushButton_arp.clicked.connect(self.start_arp_thread)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "ping"))
        self.ping_t.setText(_translate("mainWindow", "-t"))
        self.ping_a.setText(_translate("mainWindow", "-a"))
        self.label_2.setText(_translate("mainWindow", "-n"))
        self.label_3.setText(_translate("mainWindow", "-l"))
        self.ping_f.setText(_translate("mainWindow", "-f"))
        self.label_4.setText(_translate("mainWindow", "-i"))
        self.label_5.setText(_translate("mainWindow", "-r"))
        self.label_6.setText(_translate("mainWindow", "-w"))
        self.label_7.setText(_translate("mainWindow", "Конечное Имя"))
        self.pushButton_ping.setText(_translate("mainWindow", "Выполнить"))
        self.label_8.setText(_translate("mainWindow", "ipconfig"))
        self.ipconfig_q.setText(_translate("mainWindow", "/?"))
        self.ipconfig_all.setText(_translate("mainWindow", "/all"))
        self.label_9.setText(_translate("mainWindow", "/release [адаптер]"))
        self.ipconfig_release_all.setText(_translate("mainWindow", "/release (все адаптеры)"))
        self.label_10.setText(_translate("mainWindow", "/renew [адаптер]"))
        self.ipconfig_renew_all.setText(_translate("mainWindow", "/renew (все адаптеры)"))
        self.ipconfig_flushdns.setText(_translate("mainWindow", "/flushdns"))
        self.ipconfig_displaydns.setText(_translate("mainWindow", "/displaydns"))
        self.ipconfig_registerdns.setText(_translate("mainWindow", "/registerdns"))
        self.label_11.setText(_translate("mainWindow", "/showclassid [адаптер]"))
        self.label_12.setText(_translate("mainWindow", "/setclassid [адаптер]"))
        self.label_13.setText(_translate("mainWindow", "устанавливаемый код класса dhcp"))
        self.pushButton_ipconfig.setText(_translate("mainWindow", "Выполнить"))
        self.label_14.setText(_translate("mainWindow", "tracert"))
        self.tracert_d.setText(_translate("mainWindow", "-d"))
        self.label_15.setText(_translate("mainWindow", "-h"))
        #self.label_16.setText(_translate("mainWindow", "-j"))
        self.label_17.setText(_translate("mainWindow", "-w"))
        self.label_18.setText(_translate("mainWindow", "Конечное Имя"))
        self.pushButton_tracert.setText(_translate("mainWindow", "Выполнить"))
        self.label_19.setText(_translate("mainWindow", "arp"))
        self.arp_s.setText(_translate("mainWindow", "-s"))
        self.arp_d.setText(_translate("mainWindow", "-d"))
        self.arp_a.setText(_translate("mainWindow", "-a"))
        self.label_20.setText(_translate("mainWindow", "inet_addr"))
        self.label_21.setText(_translate("mainWindow", "eth_addr"))
        self.label_22.setText(_translate("mainWindow", "eth_addr"))
        self.label_23.setText(_translate("mainWindow", "-N if_addr"))
        self.pushButton_arp.setText(_translate("mainWindow", "Выполнить"))


    def arp(self):
        arp_arr = []
        if self.arp_s.isChecked():
            arp_arr.append("-s")
            if self.arp_inet_addr.toPlainText() != "":
                arp_arr.append(self.arp_inet_addr.toPlainText())
                if self.arp_eth_addr.toPlainText() != "":
                    arp_arr.append(self.arp_eth_addr.toPlainText())
                    if self.arp_if_addr.toPlainText() != "":
                        arp_arr.append(self.arp_if_addr.toPlainText())
        elif self.arp_d.isChecked():
            arp_arr.append("-d")
            if self.arp_inet_addr.toPlainText() != "":
                arp_arr.append(self.arp_inet_addr.toPlainText())
                if self.arp_if_addr.toPlainText() != "":
                    arp_arr.append(self.arp_if_addr.toPlainText())
        elif self.arp_a.isChecked():
            arp_arr.append("-a")
            if self.arp_inet_addr.toPlainText() != "":
                arp_arr.append(self.arp_inet_addr.toPlainText())
            if self.arp__n_if_addr.toPlainText() != "":
                arp_arr.append("-N")
                arp_arr.append(self.arp__n_if_addr.toPlainText())

        if len(arp_arr) == 0:
            arp_arr.append("arp")
        else:
            arp_arr.insert(0, "arp ")

        process = subprocess.Popen(
            arp_arr,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='cp866'
        )
        print(process.args)

        self.graf = nx.Graph()

        while True:
            line = process.stdout.readline()
            if not line or self.stop_threads == True:
                break
            self.update_output(line)

            parts = line.split()
            if len(parts) == 3:
                ip_address = parts[0]
                mac_address = parts[1]
                self.graf.add_node(ip_address)
                self.graf.add_edge(ip_address, mac_address)




    def start_arp_thread(self):
        try:
            self.stop_threads = True
            self.thread.join()
        except Exception as e:
            print(e)
            pass
        self.thread = threading.Thread(target=self.arp)
        self.stop_threads = False
        self.output.clear()
        self.thread.start()
        self.thread.join()
        #time.sleep(0.01)
        # Визуализировать граф
        pos = nx.spring_layout(self.graf, k=0.8)
        nx.draw(self.graf, pos, with_labels=True, node_size=2500, node_color='skyblue', font_size=10)
        plt.title("Граф сети на основе таблицы ARP")
        plt.show()



    def tracert(self):
        tracert_arr = []
        if self.tracert_d.isChecked():
            tracert_arr.append("-d ")
        if self.tracert_h.value() != 0:
            tracert_arr.append("-h ")
            tracert_arr.append(str(self.tracert_h.value()))
        #if self.tracert_j.value() != 0:
         #   tracert_arr.append("-j ")
          #  tracert_arr.append(str(self.tracert_j.value()))
        if self.tracert_w.value() != 0:
            tracert_arr.append("-w ")
            tracert_arr.append(str(self.tracert_w.value()))
        if self.tracert_ip.toPlainText() != "":
            tracert_arr.append(str(self.tracert_ip.toPlainText()))
        if len(tracert_arr) == 0:
            tracert_arr.append("tracert")
        else:
            tracert_arr.insert(0, "tracert ")

        process = subprocess.Popen(
            tracert_arr,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='cp866'
        )
        print(process.args)

        while True:
            line = process.stdout.readline()
            if not line or self.stop_threads == True:
                break
            self.update_output(line)

    def start_tracert_thread(self):
        try:
            self.stop_threads = True
            self.thread.join()
        except Exception as e:
            print(e)
            pass
        self.thread = threading.Thread(target=self.tracert)
        self.stop_threads = False
        self.output.clear()
        self.thread.start()



    def ipconfig(self):
        ipconfig_arr = []
        if self.ipconfig_q.isChecked():
            ipconfig_arr.append("/? ")
        if self.ipconfig_all.isChecked():
            ipconfig_arr.append("/all")
        if self.ipconfig_renew_all.isChecked():
            ipconfig_arr.append("/renew")
        if self.ipconfig_release_all.isChecked():
            ipconfig_arr.append("/release")
        if self.ipconfig_flushdns.isChecked():
            ipconfig_arr.append("/flushdns")
        if self.ipconfig_displaydns.isChecked():
            ipconfig_arr.append("/displaydns")
        if self.ipconfig_registerdns.isChecked():
            ipconfig_arr.append("/registerdns")

        release = self.ipconfig_release_adapter.toPlainText()
        if release != "":
            ipconfig_arr.append("/release")
            ipconfig_arr.append(release)
        renew = self.ipconfig_renew_adapter.toPlainText()
        if renew != "":
            ipconfig_arr.append("/renew")
            ipconfig_arr.append(renew)
        showclassid = self.ipconfig_showclassid.toPlainText()
        if showclassid != "":
            ipconfig_arr.append("/showclassid")
            ipconfig_arr.append(showclassid)
        setclassid = self.ipconfig_setclassid.toPlainText()
        if setclassid != "":
            ipconfig_arr.append("/setclassid")
            ipconfig_arr.append(setclassid)
            setclassid_code = self.ipconfig_setclassid_2.toPlainText()
            if setclassid != "":
                ipconfig_arr.append(setclassid_code)

        if len(ipconfig_arr) == 0:
            ipconfig_arr.append("ipconfig")
        else:
            ipconfig_arr.insert(0, "ipconfig ")

        process = subprocess.Popen(
            ipconfig_arr,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='cp866'
        )
        print(process.args)
        while True:
            line = process.stdout.readline()
            if not line or self.stop_threads == True:
                break
            self.update_output(line)

    def start_ipconfig_thread(self):
        try:
            self.stop_threads = True
            self.thread.join()
        except Exception as e:
            print(e)
            pass
        self.thread = threading.Thread(target=self.ipconfig)
        self.stop_threads = False
        self.output.clear()
        self.thread.start()

    def ping(self):
        ping_arr = []
        if self.ping_t.isChecked():
            ping_arr.append("-t ")
        if self.ping_a.isChecked():
            ping_arr.append("-a ")
        if self.ping_n.value() != 0:
            ping_arr.append("-n ")
            ping_arr.append(str(self.ping_n.value()))
        if self.ping_l.value() != 0:
            ping_arr.append("-l ")
            ping_arr.append(str(self.ping_l.value()))
        if self.ping_f.isChecked():
            ping_arr.append("-f ")
        if self.ping_i.value() != 0:
            ping_arr.append("-i ")
            ping_arr.append(str(self.ping_i.value()))
        if self.ping_r.value() != 0:
            ping_arr.append("-r ")
            ping_arr.append(str(self.ping_r.value()))
        if self.ping_w.value() != 0:
            ping_arr.append("-w ")
            ping_arr.append(str(self.ping_w.value()))
        host = self.ip.toPlainText()
        if host != '':
            ping_arr.append(host)
        if len(ping_arr) == 0:
            ping_arr.append("ping")
        else:
            ping_arr.insert(0, "ping ")

        # Выполните команду ping с дополнительными параметрами
        process = subprocess.Popen(
            ping_arr,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='cp866'
        )
        print(process.args)
        while True:
            line = process.stdout.readline()
            if not line or self.stop_threads == True:
                break
            self.update_output(line)

    def start_ping_thread(self):
        try:
            self.stop_threads = True
            self.thread.join()
        except Exception as e:
            print(e)
            pass
        self.thread = threading.Thread(target=self.ping)
        self.stop_threads = False
        self.output.clear()
        self.thread.start()

    def update_output(self, text):
        time.sleep(0.01)
        self.output.append(text)
        self.output.verticalScrollBar().setValue(self.output.verticalScrollBar().maximum())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
